# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: BNE
title: "BNE: Brand New Engineers"
email: it@brandnewengineers.rs
lang: sr_Latn
encoding: utf-8
author: EESTEC LC Belgrade
baseurl: /
description: >- # this means to ignore newlines until "url:"
  "Brand New Engineers - Od integrala do inženjera!“
  je projekat koji čine konferencija, dva hakatona i takmičenje iz robotike.
  Na konferenciji se održavaju predavanja o aktuelnim inženjerskim temama.
  Projekat organizuje EESTEC
url: https://brandnewengineers.rs
facebook:
  publisher: BrandNewEngineers
logo: /img/logo.png
social:
  name: Brand New Engineers
  links:
    - https://www.facebook.com/BrandNewEngineers
sass:
  sass_dir: _sass
  style: compressed
exclude: ['archives', 'docs','Gemfile','Gemfile.lock','node_modules','bne.iml','php/data']

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "img"
    values:
      image: true
